<script src="assets/template/scripts/libs/jquery/dist/jquery.min.js"></script>
<script src="assets/template/scripts/moment-timezone.js"></script>
<script src="assets/template/scripts/libs/swiper/dist/js/swiper.jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/locales.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.3.0/moment-timezone.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.3.0/moment-timezone-utils.min.js"></script>
<script src="assets/template/scripts/sticky.js"></script>
<script src="assets/template/scripts/front-clock.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBNIxXO_SrSX_b5mDkAa-nep-O7AuFn1WQ&amp;callback=initMap"></script>
<script src="assets/template/scripts/main.js"></script>